version: '3.8'

services:
  crawler:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./tmp:/web_crawler/tmp
    entrypoint: ["/web_crawler/target/release/crw", "https://stackoverflow.com/"]
    environment:
      - "RUST_LOG=info"
